const {GoogleGenAI} = require("@google/genai")
const {z}= require('zod')
const {zodToJsonSchema}= require("zod-to-json-schema")

const ai= new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY

})

const interviewReportSchema= z.object({
    matchScore: z.number().describe("A score between 0 to 100 indicating how well the candidate's profile matches the job description "),
    technicalQuestions: z.array(z.object({
        question: z.string().describe("The technical question that can be asked in the interview"),
        intention: z.string().describe("The intention of interviewer behind asking this question"),
        answer: z.string().describe("How to answer this question, what points to cover, what approach to take.")
    })).describe("Technical questions that can be asked in the interview along with their intention and how to answer them"),
    behaviouralQuestions: z.array(z.object({
        question: z.string().describe("The behavioural question that can be asked in the interview"),
        intention: z.string().describe("The intention of interviewer behind asking this question"),
        answer: z.string().describe("How to answer this question, what points to cover, what approach to take.")
    })).describe("Behavioural questions that can be asked in the interview along with their intention and how to answer them"),
    skillGaps: z.array(z.object({
        skill: z.string().describe("The skill which the candidate is lacking"),
        severity: z.enum(["low","medium","high"]).describe("The severity of the skill gap i.e how much it is impprtant from the job description")
    })).describe("List of skill gaps in the candidate's profile along with their severity"),
    preparationPlan: z.array(z.object({
        day: z.number().describe("The day number in the preparation plan starting from 1, prefer giving 7 days preparation plan"),
        focus: z.string().describe("The main focus of this day in the preparation plan e.g data structures & mock interviews"),
        tasks: z.array(z.string()).describe("List of tasks that can be done in this day to follow the preparation plan e.g study a specific topic of data structures or system design etc")
    })).describe("A day-wise preparation plan for the candidate to follow the order to prepare for the interview effectively"),
    title: z.string().describe("The title of the job for which the interview report is generated")
})

async function generateInterviewReport({resume,selfDescription,jobDescription}){

    const prompt=`Generate an interview report for a candidate with the following details:
                    Resume: ${resume}
                    Self description: ${selfDescription}
                    job Description: ${jobDescription}
                    `

    const response= await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents:prompt,
        config:{
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(interviewReportSchema),

        }
    })

    return JSON.parse(response.text)
}


async function generatePdfFromHtml(htmlContent){
    const browser= await puppeteer.launch()
    const page= await browser.newPage()
    await page.setContent(htmlContent,{waitUntil: "networkidle0"})

    const pdfBuffer= await page.pdf({
        format:"A4", margin: {
            top: "10mm",
            bottom: "10mm",
            left: "7mm",
            right: "7mm"
        }
    })
    await browser.close()
    return pdfBuffer
}

async function generateResumePdf({resume,jobDescription,selfDescription}){

    const resumePdfSchema= z.object({
        html: z.string().describe("The html content of resume(of one page) which can be converted to PDF using any library like puppeteer")
    })

    const prompt =`Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
    `
    const response= await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config:{
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(resumePdfSchema)
        }
    })

    const jsonContent= JSON.parse(response.text)
    const pdfBuffer= await generatePdfFromHtml(jsonContent.html)

    return pdfBuffer
}


module.exports= {generateInterviewReport,generateResumePdf}
